version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
    - location: scripts/app_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
# for deploy
